apiVersion: v1
kind: Deployment
metadata:
  name: aks-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: 6421/docker-test.$BUILD_ID
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
